yaml
Copy code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{ .Values.command }}
          volumeMounts: {{ .Values.volumeMounts }}
      volumes: {{ .Values.volumes }}

